<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search field_tnb-google-search-input</name>
   <tag></tag>
   <elementGuidId>b782ea68-5e6e-4d18-9fa7-23de12b01796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tnb-google-search-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tnb-google-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>992f3429-1323-4b6f-bb82-b98ee9f6788c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tnb-google-search-input</value>
      <webElementGuid>9ab89bc9-0a9f-4d1d-92c2-e36725f1eee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43dae17b-dfd9-4ae5-b686-7e7f38c43e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>654fb6e9-570a-4b6b-ad44-5337e88c2314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9accce14-89dc-4c8e-a8ce-fb6dafa0c4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>TopNavBar.googleSearchAttachKeyPressHandler(event)</value>
      <webElementGuid>f1c939e5-d5d6-4dd4-aec8-1f9a196b1f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search field</value>
      <webElementGuid>c480f4ad-5a9c-498c-aa43-fc3e81671a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.searchWithSuggestions(this)</value>
      <webElementGuid>bee4ee05-640b-4e29-8f92-2ab469747724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>TopNavBar.searchWithSuggestions(this)</value>
      <webElementGuid>7892ffa5-3a8d-4b4c-9b69-194d19be48f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>TopNavBar.searchFieldLostFocus(event)</value>
      <webElementGuid>4cd00e24-1f0f-49f3-acfb-3aeb96362a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tnb-google-search-input&quot;)</value>
      <webElementGuid>7be56a1a-332c-46f8-bc7c-51ca3a9b47e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tnb-google-search-input']</value>
      <webElementGuid>55b197c2-e4f0-4bec-a7fc-563a260e0f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tnb-google-search-inner-container']/input</value>
      <webElementGuid>f2d13296-a06e-46d2-a61f-c835dddd9aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e85fe9b3-beff-4429-a82d-abfe356f640f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tnb-google-search-input' and @type = 'text' and @placeholder = 'Search...']</value>
      <webElementGuid>0fc6492f-f9b0-41c5-ba2b-d409d8c7fcf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
