<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Consulting</name>
   <tag></tag>
   <elementGuidId>3b2d3839-5297-4557-8859-2d019978fe04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-114021']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-114021 > a.menu-item.menu-item-type-post_type.menu-item-object-page.sub-menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Primary&quot;i >> internal:role=link[name=&quot;Consulting&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e269f58-400e-46bf-bb86-12a60ef7d091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.persistent.com/services/consulting/</value>
      <webElementGuid>490ef627-6e45-48d3-be2a-7e58fa6e8d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item menu-item-type-post_type menu-item-object-page sub-menu-link</value>
      <webElementGuid>56cc9dbb-37a5-480f-b404-6a1e0e4f1d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consulting</value>
      <webElementGuid>7c344f03-afa8-45f9-8f42-4b7292950ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-114021&quot;)/a[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page sub-menu-link&quot;]</value>
      <webElementGuid>85e5211f-4d36-4ec7-8b5f-4df5e68206d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-114021']/a</value>
      <webElementGuid>31654857-a6dc-4a8b-9d98-e6a655325947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Consulting')]</value>
      <webElementGuid>4796bc0f-1f76-4b61-a105-7ca4a0fc8724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud &amp; Infrastructure'])[1]/following::a[1]</value>
      <webElementGuid>0a7d4a52-4fdb-4b03-b524-87b2e7c74151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Development &amp; Management'])[1]/following::a[2]</value>
      <webElementGuid>e7f29dfe-dd74-4195-a25a-d392dec5d5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CX Transformation'])[1]/preceding::a[1]</value>
      <webElementGuid>1082b7fe-9a53-4881-bda9-fb6a83352dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data &amp; Analytics'])[1]/preceding::a[2]</value>
      <webElementGuid>cbf88517-7f4c-476b-a6db-b5afd49ed2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consulting']/parent::*</value>
      <webElementGuid>4b756c1e-c073-4e06-97c5-f4c3a21c806b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.persistent.com/services/consulting/')]</value>
      <webElementGuid>7007f745-b360-421f-bcab-478cfdcf87ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[3]/a</value>
      <webElementGuid>b402c461-aea7-4a93-af22-2a0c1acedb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.persistent.com/services/consulting/' and (text() = 'Consulting' or . = 'Consulting')]</value>
      <webElementGuid>c14fd92a-8e11-4327-8f6a-5702a6e25f10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
