<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Careers</name>
   <tag></tag>
   <elementGuidId>e62c875e-0fe0-428e-ac3b-7538bd93106f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-17137']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-17137 > a.menu-item.menu-item-type-custom.menu-item-object-custom.nav-link.white-outline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Primary&quot;i >> internal:role=link[name=&quot;Careers&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9736e91f-49f2-4248-a4b7-b623d761579c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6bd092ea-8a47-4a01-abd1-59ea1f5fbe6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://careers.persistent.com/</value>
      <webElementGuid>3b339ecb-47ac-44a8-b2e7-275e2cf7cfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item menu-item-type-custom menu-item-object-custom nav-link white-outline</value>
      <webElementGuid>c599f20d-892a-44af-a41b-935593e7150f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Careers</value>
      <webElementGuid>4035df5d-1343-4161-b280-5a6bc4b93c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-17137&quot;)/a[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom nav-link white-outline&quot;]</value>
      <webElementGuid>487ca1ce-075f-4506-804e-2c8766bf36a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-17137']/a</value>
      <webElementGuid>10423aa7-97b5-45de-91e2-836ab2c9634d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Careers')]</value>
      <webElementGuid>5353f71e-19e0-47f5-9676-d9265b250111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Innovation Labs'])[1]/following::a[1]</value>
      <webElementGuid>23407d7b-2362-4bcf-a3b9-9befe5a6a95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Releases'])[1]/following::a[2]</value>
      <webElementGuid>21dca46c-1337-4bb3-ad51-05c6dadf126e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::a[1]</value>
      <webElementGuid>79980cde-d1cd-4717-9788-87bbebd9392d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[2]</value>
      <webElementGuid>3060ec83-8d80-4b93-91d8-91f926331e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Careers']/parent::*</value>
      <webElementGuid>0c83f4d4-86b3-4c67-b5ff-558c79bef1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://careers.persistent.com/')]</value>
      <webElementGuid>bf561619-7382-4426-862f-a671fcf13927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>d4e70a01-43ff-4968-a534-6aa7e358622e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://careers.persistent.com/' and (text() = 'Careers' or . = 'Careers')]</value>
      <webElementGuid>ad21c706-98e7-4a1c-adf7-c44c12bc2ce1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
