<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Object Definitions</name>
   <tag></tag>
   <elementGuidId>f7dab088-1daa-45cb-9e8c-85e95c9c31e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftmenuinnerinner']/a[91]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(91)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Object Definitions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8e02e1e-a7ef-469d-b894-8e4e7fd751bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>b585d2cd-acf4-498f-a919-a86c940696b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>js_object_definition.asp</value>
      <webElementGuid>ee511382-ee99-4d1f-9147-00d6161d9df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Object Definitions</value>
      <webElementGuid>67562bc5-61b6-44d0-84c7-d168d0516fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftmenuinnerinner&quot;)/a[91]</value>
      <webElementGuid>7283c28e-2e87-4681-aa99-699f6355c103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftmenuinnerinner']/a[91]</value>
      <webElementGuid>3d1bba6a-3869-4492-b0f2-f4b02db7fcab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Object Definitions')]</value>
      <webElementGuid>e07954a6-766f-44ce-96e2-3efa4c18d706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS Objects'])[2]/following::a[1]</value>
      <webElementGuid>77a604ce-f0a9-490b-8e73-b4752680f5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JS History'])[1]/following::a[1]</value>
      <webElementGuid>dc6b2173-9580-4142-a83f-d2c5689ef2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object Prototypes'])[1]/preceding::a[1]</value>
      <webElementGuid>2c832149-ee9f-45db-91c6-36108f3c57db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object Methods'])[1]/preceding::a[2]</value>
      <webElementGuid>d6b93e7e-4703-4c32-9087-9e8d12a6384d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Object Definitions']/parent::*</value>
      <webElementGuid>cf8beb10-5d1b-4691-a087-d42e512ff21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'js_object_definition.asp')]</value>
      <webElementGuid>2c263843-63d4-4b9e-886e-ae2d36026299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[91]</value>
      <webElementGuid>dde4bc1d-be0f-4632-b47d-d80b91bba2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'js_object_definition.asp' and (text() = 'Object Definitions' or . = 'Object Definitions')]</value>
      <webElementGuid>cbac2f3e-c001-43a3-a6cc-bbfbc72edbea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
