<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PHP</name>
   <tag></tag>
   <elementGuidId>e863d88e-d4a7-46a6-80c8-f343ecf08a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subtopnav']/a[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PHP&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6385621f-8f9a-46b9-9bb9-1ca93730c131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/php/default.asp</value>
      <webElementGuid>92ff0d5b-f318-4938-bb82-654b53489d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ga-nav</value>
      <webElementGuid>43fbf1b8-3a93-4db2-a12e-fd64399d2a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PHP Tutorial</value>
      <webElementGuid>cbb27327-6d36-4189-bfe0-27b842061454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PHP</value>
      <webElementGuid>6f0f8e56-87c4-4c5f-81b2-6b1f4d18d4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subtopnav&quot;)/a[@class=&quot;ga-nav&quot;]</value>
      <webElementGuid>5cbca3a0-1312-40f2-bb80-aa4580841f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subtopnav']/a[7]</value>
      <webElementGuid>a3148e1e-bced-483f-89c4-3799b5f76c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'PHP')])[3]</value>
      <webElementGuid>4fa15ee4-f693-42c3-831f-17518dbec05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAVA'])[1]/following::a[1]</value>
      <webElementGuid>28fbee8f-5201-4226-a2e6-71c125367f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PYTHON'])[1]/following::a[2]</value>
      <webElementGuid>2a934b17-9bf6-480b-b85b-fbd57dd7bdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOW TO'])[1]/preceding::a[1]</value>
      <webElementGuid>3bfd3aa4-0b3f-4a8e-9016-d52c9f83ceb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W3.CSS'])[2]/preceding::a[2]</value>
      <webElementGuid>6e18ebe3-e28b-47a8-ac20-f0ec37abd153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/php/default.asp')])[3]</value>
      <webElementGuid>c653e1bb-986e-4a04-bf11-228583811194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a[7]</value>
      <webElementGuid>bec2a2ad-0da1-49ac-8982-b0d81a7ec6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/php/default.asp' and @title = 'PHP Tutorial' and (text() = 'PHP' or . = 'PHP')]</value>
      <webElementGuid>460e3d60-7308-4c8e-b907-ffb77031518f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
